@startuml

footer: **Figure 1: Docker Image Hierarchy**

object scratch #bbb {
explicitly empty image
}
object debian #fff {
install linux OS
}
object openjdk #fff {
install java
}
object cluster_base {
install python3
define shared_workspace
}
object jupyterlab {
install pyspark
install jupyterlab
expose port 8888
run Jupyter Lab
}
object spark_base {
specify spark version
specify hadoop version
download and install spark
set environment variables
}
object spark_master {
expose master port 7077
expose master web_ui port 8080
run Spark Master
record master logs
}
object spark_worker {
expose worker port 8081
run Spark Worker
record worker logs
}

scratch <|-- debian : (makes explicit)
debian <|- openjdk : built from
openjdk <|-- cluster_base : built from
cluster_base <|- spark_base : built from
cluster_base <|-- jupyterlab : built from
spark_base <|-- spark_master : built from
spark_base <|-- spark_worker : built from



@enduml
