version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: ${BUILDER}/jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ${PWD}/files:/opt/workspace
  spark-master:
    image: ${BUILDER}/spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - ${PWD}/files:/opt/workspace
  spark-worker-1:
    image: ${BUILDER}/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ${PWD}/files:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: ${BUILDER}/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ${PWD}/files:/opt/workspace
    depends_on:
      - spark-master
